// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	domain_user "github.com/felixa1996/go_next_be/app/domain/user"
	domain_user_dto "github.com/felixa1996/go_next_be/app/domain/user/dto"

	mock "github.com/stretchr/testify/mock"
)

// UserUsecaseContract is an autogenerated mock type for the UserUsecaseContract type
type UserUsecaseContract struct {
	mock.Mock
}

// Create provides a mock function with given fields: _a0, _a1
func (_m *UserUsecaseContract) Create(_a0 context.Context, _a1 domain_user_dto.UserDtoCreateInput) (domain_user.User, error) {
	ret := _m.Called(_a0, _a1)

	var r0 domain_user.User
	if rf, ok := ret.Get(0).(func(context.Context, domain_user_dto.UserDtoCreateInput) domain_user.User); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(domain_user.User)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, domain_user_dto.UserDtoCreateInput) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: _a0, _a1
func (_m *UserUsecaseContract) Delete(_a0 context.Context, _a1 domain_user_dto.UserDtoDeleteInput) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain_user_dto.UserDtoDeleteInput) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindOne provides a mock function with given fields: _a0, _a1
func (_m *UserUsecaseContract) FindOne(_a0 context.Context, _a1 domain_user_dto.UserDtoFindOneInput) (domain_user.User, error) {
	ret := _m.Called(_a0, _a1)

	var r0 domain_user.User
	if rf, ok := ret.Get(0).(func(context.Context, domain_user_dto.UserDtoFindOneInput) domain_user.User); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(domain_user.User)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, domain_user_dto.UserDtoFindOneInput) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindPagination provides a mock function with given fields: _a0
func (_m *UserUsecaseContract) FindPagination(_a0 context.Context) ([]domain_user.User, error) {
	ret := _m.Called(_a0)

	var r0 []domain_user.User
	if rf, ok := ret.Get(0).(func(context.Context) []domain_user.User); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain_user.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: _a0, _a1, _a2
func (_m *UserUsecaseContract) Update(_a0 context.Context, _a1 domain_user_dto.UserDtoUpdateParamInput, _a2 domain_user_dto.UserDtoUpdateInput) (domain_user.User, error) {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 domain_user.User
	if rf, ok := ret.Get(0).(func(context.Context, domain_user_dto.UserDtoUpdateParamInput, domain_user_dto.UserDtoUpdateInput) domain_user.User); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Get(0).(domain_user.User)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, domain_user_dto.UserDtoUpdateParamInput, domain_user_dto.UserDtoUpdateInput) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewUserUsecaseContract interface {
	mock.TestingT
	Cleanup(func())
}

// NewUserUsecaseContract creates a new instance of UserUsecaseContract. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUserUsecaseContract(t mockConstructorTestingTNewUserUsecaseContract) *UserUsecaseContract {
	mock := &UserUsecaseContract{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
